name: Deploy WordPress to InfinityFree

on:
  push:
    branches:
      - main  # Change this if your branch is different

jobs:
  ftp-deploy:
    name: Upload WordPress to InfinityFree
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/  # Ensure this is correct
        local-dir: ./  # Adjust if necessary
